name: Validate remote config

on:
  push:
    branches: [ main ]
    paths:
      - 'config/**/*.json'
      - 'schema/**/*.json'
      - '.github/workflows/validate.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'config/**/*.json'
      - 'schema/**/*.json'
      - '.github/workflows/validate.yml'
  workflow_dispatch: {}  # allow manual runs from Actions tab

jobs:
  ajv-validate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g ajv-cli@5
      - run: ajv -s schema/config.schema.json -d 'config/*.json' --spec=draft2020
